### ISSUE TITLE
Updating a package that expanded its `Package-Requires`?

### ISSUE THREAD

**Issue by greghendershott** [rranelli/auto-package-update.el#14]
Please see [issue 88 on racket-mode](https://github.com/greghendershott/racket-mode/issues/88).

Recently my package added some dependencies: dash, faceup, s.

I [updated my `Package-Requires`](https://github.com/greghendershott/racket-mode/blob/master/racket-mode.el#L6) to include them.

But when running auto-package-update, a mutual user of ours got:

```
Warning (emacs): Unable to activate package racket-mode'. Required packagefaceup-0.0.2' is unavailable
Warning (emacs): Unable to activate package racket-mode'. Required packages-1.9.0' is unavailable
```

I'm trying to figure out if I did something wrong, or, if this is maybe an issue with `auto-package-update`?

Note: On a VM that had the older racket-mode, I tried the usual process in the `*Packages*` buffer.  It did did recognize and install the new dependencies.

**Comment by rranelli** [comment]
Looks like this wasn't an issue with `auto-package-update` so I'm going to close this.
@greghendershott, thanks for stopping by ;)

**Comment by greghendershott** [comment]
:+1: I should have remembered to come back and close this myself. Thanks again for your help.
