### ISSUE TITLE
Ability to specify the time packages are updated

### ISSUE THREAD

**Issue by AlexChesters** [rranelli/auto-package-update.el#19]
It would be quite nice to be able to specify the time packages are updated

**Comment by rranelli** [comment]
hm, I don't see myself using it, but that might be nice.

Do you intend to do something like checking for updates every day at, say, 3 a.m. ? Since package updates block the world and take quite some time, I think that might be the more reasonable use for the feature.

**Comment by AlexChesters** [comment]
Yeah, that's exactly what I meant, I probably didn't articulate it very well 8-)

**Comment by rranelli** [comment]
Alright, I will have a take at this when I get some free time o/

**Comment by AlexChesters** [comment]
Cool, cheers!

**Comment by rranelli** [comment]
@AlexChesters, done at be83ab1 using the great `timer.el` built-in library. This will probably be available at Melpa in a few hours as version 1.5.

I think this will probably suit you, right?

Thanks !

**Comment by AlexChesters** [comment]
Thanks @rranelli! Exactly what I wanted :-)
