### ISSUE TITLE
"too many arguments" error

### ISSUE THREAD

**Issue by pervezfunctor** [rranelli/auto-package-update.el#22]
After the recent update(sep 28th), emacs shows this error at startup. Culprit seems to be 

(defvar apu--last-update-day-filename
  ".last-package-update-day"
  "Name of the file in which the last update day is going to be stored."
  :type 'string
  :group 'auto-package-update)

Perhaps, it should be defcustom instead of defvar?

**Comment by rranelli** [comment]
You're definitely right.

Just fixed it o/

Thanks
