### ISSUE TITLE
Update should respect dependencies between packages

### ISSUE THREAD

**Issue by jacobilsoe** [rranelli/auto-package-update.el#25]
If two packages, A and B, are due to be updated and A depends on B then B should be updated first and then A. Right now the update order seems to be determined by the ordering in `package-activated-list`.

**Comment by rranelli** [comment]
Have you seen this yield some kind of problem?

I never noticed any. (I think there might be problems with byte compilation, but I don't know enough to be sure)

**Comment by jacobilsoe** [comment]
Well, I just got an error updating magit:

Error installing with-editor
Error installing magit-popup
magit up to date.

If I do it (U and then x) from `list-packages` everything works just fine. So I am not sure it is a dependency problem, but something is different when using apu.

**Comment by jacobilsoe** [comment]
My bad. I had some bad elc files (pointing to files in a non-existing directory). I just found it a bit strange that apu did not work when `list-packages` did.

**Comment by rranelli** [comment]
no problem :)

Thanks for using the package and documenting the issue for future reference :+1:
