### ISSUE TITLE
Prompt before attempting update

### ISSUE THREAD

**Issue by ekenberg** [rranelli/auto-package-update.el#27]
I have _auto-package-update-interval_ set to 3 days and run _auto-package-update-maybe_ in Emacs startup process. Sometimes when I'm in a real hurry, Emacs decides to start some huge list of automatic upgrades. It would be very convenient to get a _y-or-n-p_ prompt before, to be able to temporarily skip updates at that time.

Something like _(setq auto-package-update-maybe-prompt-before-update t)_ in init.el would be awesome! Possible to add?

All the best!

**Comment by rranelli** [comment]
Looks like a sensible addition. 

I'll work on it as soon as I get some time. You're welcome to try giving it a shot too :)

cheers

**Comment by rranelli** [comment]
fixed via #29
