### ISSUE TITLE
Request async update process instead of sync one

### ISSUE THREAD

**Issue by nedijahij** [rranelli/auto-package-update.el#39]
I do really like this package but sometime it's a bit annoying when i open Emacs and it stuck fetching and updating my package. So, can this package make an update for async process instead of using sync process? thanks.

**Comment by FrostyX** [comment]
If this is implement-able, it would be an awesome feature.
For me, the package update causes big enough lag to disconnect me from IRC.

**Comment by FrostyX** [comment]
Awesome, thank you very much @rranelli.
At your convenience, could you please create also async version of `auto-package-update-at-time`?

**Comment by gsingh93** [comment]
@FrostyX I need to do a bit more testing locally, but I tried to add this here: https://github.com/rranelli/auto-package-update.el/pull/54
